### PR TITLE
added bubble sort function

### PR DESCRIPTION
**Pull request by grace-mugoiri**

### CODE REVIEW

**Comment by dipto0321** [comment]
# So far so good 🚀 👏 👀 

Hi @grace-mugoiri ,

Good job 👏 . I liked the optimization. Also, the code is clean. I found these issues.
### bubble_sort

This method is okay.

### bubble_sort_by

It will be better if you don't use `for loop` for this
```
        for i in (0..n) do
            if yield(array[i], array[i + 1]) > 0
            array[i], array[i + 1] = array[i + 1], array[i]
            sorted = false
            end
        end
```
You can simply use `each` like this

```
(0..n).each do |i|
      if yield(array[i], array[i + 1]) > 0
        array[i], array[i + 1] = array[i + 1], array[i]
        sorted = false
      end
    end
```
Remove puts from `puts array` [here](https://github.com/grace-mugoiri/ruby-bubble-sort/blob/27fbe29a836700653e68b91e7edef7152e570b38/bubble_sort_by.rb#L14)

You can test the `bubble_sort_by` this way:

```
print bubble_sort_by(["hi","hello","hey"]) {|left,right| left.length - right.length }
```

Please apply robocop styles and also try to use stickler CI. After fixing all the issues please send another request to re-review this project.

Thanks 🙏

**Comment by grace-mugoiri** [comment]
Hey @dipto0321 I realised when i remove the "puts array", the function does not print the tests

**Comment by dipto0321** [comment]
> Hey @dipto0321 I realized when I remove the "puts array", the function does not print the tests

Hi @grace-mugoiri ,

I told you to remove `puts` not whole `puts array`. It will look like this:

```
def bubble_sort_by(array)
    n = array.length - 2
    loop do
        sorted = true
        for i in (0..n) do
            if yield(array[i], array[i + 1]) > 0
            array[i], array[i + 1] = array[i + 1], array[i]
            sorted = false
            end
        end
        break if sorted
        n -= 1
    end
    array 
 end
```
☝️ 

Thanks 🙏

**Comment by grace-mugoiri** [comment]
Deleted the puts on line 14 so it just returns array, @dipto0321 it should be fine now.

**Comment by dipto0321** [comment]
Hi @grace-mugoiri ,

All is good now. You can merge it into the master. this is from me 👍 

Thanks 🙏

**Pull request merged**
